services:
  - type: web
    name: instagram-reel-uploader
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      cd backend
      ls -la
      python --version
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt -v
    startCommand: "cd backend && python test.py"  # Changed temporarily
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
