services:
  - type: web
    name: instagram-reel-uploader
    env: python
    plan: free
   buildCommand: |
  cd backend
  /opt/render/project/src/.venv/bin/python -m pip install -r requirements.txt
startCommand: |
  cd backend
  /opt/render/project/src/.venv/bin/python -m uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
