services:
  - type: web
    name: instagram-reel-uploader
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
    startCommand: |
      cd backend
      python --version
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
      python test.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
